export function buildResourceTableColumns(t: (key: string) => string): Record<string, Array<{ key: string; label: string }>> {
  return {
    nodes: [
      { key: "name", label: t("col.name") },
      { key: "status", label: t("col.status") },
      { key: "roles", label: "Roles" },
      { key: "nodeResources", label: "Usage" },
      { key: "labelsText", label: "Labels" },
      { key: "kubeletVersion", label: t("col.kubernetes") },
      { key: "createdAt", label: t("col.age") },
    ],
    namespaces: [
      { key: "name", label: t("col.name") },
      { key: "status", label: t("col.status") },
      { key: "namespaceResources", label: "Usage" },
      { key: "createdAt", label: t("col.age") },
    ],
    pods: [
      { key: "namespace", label: t("col.namespace") },
      { key: "name", label: t("col.name") },
      { key: "phase", label: t("col.phase") },
      { key: "ready", label: t("col.ready") },
      { key: "containers", label: t("col.containers") },
      { key: "restarts", label: t("col.restarts") },
      { key: "podResources", label: "Usage" },
      { key: "node", label: t("col.node") },
      { key: "createdAt", label: t("col.age") },
    ],
    deployments: [
      { key: "namespace", label: t("col.namespace") },
      { key: "name", label: t("col.name") },
      { key: "status", label: t("col.status") },
      { key: "ready", label: t("col.ready") },
      { key: "updated", label: t("col.updated") },
      { key: "available", label: t("col.available") },
      { key: "createdAt", label: t("col.age") },
    ],
    replicasets: [
      { key: "namespace", label: t("col.namespace") },
      { key: "name", label: t("col.name") },
      { key: "status", label: t("col.status") },
      { key: "ready", label: t("col.ready") },
      { key: "available", label: t("col.available") },
      { key: "createdAt", label: t("col.age") },
    ],
    services: [
      { key: "namespace", label: t("col.namespace") },
      { key: "name", label: t("col.name") },
      { key: "type", label: t("col.type") },
      { key: "clusterIp", label: t("col.clusterIp") },
      { key: "ports", label: t("col.ports") },
      { key: "createdAt", label: t("col.age") },
    ],
    events: [
      { key: "namespace", label: t("col.namespace") },
      { key: "type", label: t("col.type") },
      { key: "reason", label: t("col.reason") },
      { key: "object", label: t("col.object") },
      { key: "message", label: t("col.message") },
      { key: "createdAt", label: t("col.age") },
    ],
    customresourcedefinitions: [
      { key: "group", label: t("col.group") },
      { key: "kind", label: t("col.kind") },
      { key: "plural", label: t("col.plural") },
      { key: "scope", label: t("col.scope") },
      { key: "versions", label: t("col.versions") },
      { key: "createdAt", label: t("col.age") },
    ],
  };
}
